/*
    MetaReal Compiler version 1.0.0
*/

#ifndef __MR_GENERATOR__
#define __MR_GENERATOR__

#include <optimizer/optimizer.h>

struct __GEN_RES_T /**< Result of the generate function */
{
    char *consts;           /**< Constants section of the assembly */
    char *main;             /**< Main section of the assembly */
};
typedef struct __GEN_RES_T gen_res_t; /**< Result of the generate function */

/**
 * \fn gen_res_t generate(value_t **values, uint64_t size)
 * Gets the list of values generated by the optimizer and converts it into assembly. \n
 * \param values List of values generated by the optimizer
 * \param size Size of the values list
 * \return The result of compilation as a list of assembly code blocks.
*/
gen_res_t generate(value_t **values, uint64_t size);

#endif /* __MR_GENERATOR__ */
