/**
 * @file parser.h
 * This file contains definitions of the parser that
 * converts the list of tokens generated by lexer into a list of nodes (abstract syntax tree). \n
 * All things defined in \a parser.c and this file have the \a mr_parser prefix.
*/

#ifndef __MR_PARSER__
#define __MR_PARSER__

#include <parser/node.h>
#include <error/error.h>

struct __MR_PARSER_T
{
    mr_node_t *nodes;
    mr_size_t size;

    mr_invalid_syntax_t error;
};
typedef struct __MR_PARSER_T mr_parser_t;

mr_byte_t mr_parser(mr_parser_t *res, mr_token_t *tokens);

#endif
